import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Banner } from '../components/Banner'
import { Footer } from '../components/Footer'
import { Grid } from '../components/Grid'
import { Navbar } from '../components/Navbar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Selfcare</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner />

      <main className={styles.container}>
        <Grid />
      </main>

      <Footer />
    </>
  )
}

export default Home
